#baseURL = "/"
baseURL = "https://sunfrancisco.net/"
title = "Sunfrancisco"

languageCode = "ja-JP"
#canonifyurls = true
hasCJKLanguage = true

theme="hugo-creative-portfolio-theme"

googleAnalytics = "UA-110927406-1"

[[params.navlinks]]
  name = "Gallery"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Tips"
  url = "contact/"


[params.social]
  dribbble      = "https://dribbble.com/kntrttm"
  github        = "https://github.com/kntrttm"
  facebook      = "https://www.facebook.com/kntrttm"
  linkedin      = "https://www.linkedin.com/in/kentaro-tsutsumi"
  #googleplus    = "full profile url in googleplus"
  email         = "hi@sunfrancisco.com"
  #twitter       = "full profile url in twitter"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"