#baseURL = "/"
baseURL = "https://sunfrancisco.net/"
title = "Sunfrancisco"

languageCode = "ja-JP"
#canonifyurls = true
hasCJKLanguage = true

theme="hugo-creative-portfolio-theme"

[params.social]
  dribbble      = "https://dribbble.com/kntrttm"
  facebook      = "https://www.facebook.com/kntrttm"
  #googleplus    = "full profile url in googleplus"
  email         = "hi@sunfrancisco.com"
  #twitter       = "full profile url in twitter"
  linkedin      = "www.linkedin.com/in/kentaro-tsutsumi"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github        = "https://github.com/kntrttm"