baseURL = "https://sunfrancisco.net"
#baseURL = "https://kntrttm.github.io/sunfrancisco.net"
languageCode = "en-us"
title = "Sunfrancisco"

hasCJKLanguage = true

theme="hugo-creative-portfolio-theme"